ALTER TABLE CHICAGO_PUBLIC_SCHOOLS_DATA 
ALTER COLUMN Leaders_Icon SET DATA TYPE VARCHAR(20)

SELECT CR.CASE_NUMBER, CR.PRIMARY_TYPE, CN.COMMUNITY_AREA_NAME 
FROM CHICAGO_CRIME_DATA CR
INNER JOIN CENSUS_DATA CN 
ON CR.COMMUNITY_AREA_NUMBER = CN.COMMUNITY_AREA_NUMBER 
AND CR.COMMUNITY_AREA_NUMBER = 18

SELECT CR.CASE_NUMBER, CR.PRIMARY_TYPE, CN.COMMUNITY_AREA_NAME 
FROM CHICAGO_CRIME_DATA CR
LEFT OUTER JOIN CENSUS_DATA CN 
ON CR.COMMUNITY_AREA_NUMBER = CN.COMMUNITY_AREA_NUMBER
WHERE CR.LOCATION_DESCRIPTION LIKE 'SCHOOL%'

SELECT CN.COMMUNITY_AREA_NUMBER, CR.CASE_NUMBER 
FROM CENSUS_DATA CN
FULL OUTER JOIN CHICAGO_CRIME_DATA CR 
ON CR.COMMUNITY_AREA_NUMBER = CN.COMMUNITY_AREA_NUMBER
WHERE CN.COMMUNITY_AREA_NAME 
IN ('Oakland', 'Armour Square', 'Edgewater')

SELECT S.NAME_OF_SCHOOL, S.COMMUNITY_AREA_NAME, 
S.AVERAGE_STUDENT_ATTENDANCE 
FROM CHICAGO_PUBLIC_SCHOOLS_DATA S
RIGHT OUTER JOIN CENSUS_DATA CN 
ON S.COMMUNITY_AREA_NUMBER = CN.COMMUNITY_AREA_NUMBER
WHERE CN.HARDSHIP_INDEX = 98

SELECT CR.CASE_NUMBER, CR.PRIMARY_TYPE, CN.COMMUNITY_AREA_NAME 
FROM CHICAGO_CRIME_DATA CR
LEFT OUTER JOIN CENSUS_DATA CN 
ON CR.COMMUNITY_AREA_NUMBER  = CN.COMMUNITY_AREA_NUMBER
WHERE CR.LOCATION_DESCRIPTION LIKE 'SCHOOL%'

CREATE OR REPLACE VIEW CHICAGO_PUBLIC_SCHOOLS
(School_Name, Safety_Rating, Family_Rating, Environment_Rating, 
Instruction_Rating, Leaders_Rating, Teachers_Rating)
AS SELECT NAME_OF_SCHOOL, Safety_Icon, Family_Involvement_Icon, 
Environment_Icon, Instruction_Icon, Leaders_Icon, Teachers_Icon
FROM CHICAGO_PUBLIC_SCHOOLS_DATA

SELECT * FROM CHICAGO_PUBLIC_SCHOOLS

SELECT School_Name, Leaders_Rating FROM CHICAGO_PUBLIC_SCHOOLS

CALL UPDATE_LEADERS_SCORE(609932,50)

SELECT Leaders_Icon, Leaders_Score FROM CHICAGO_PUBLIC_SCHOOLS_DATA 
WHERE School_ID = 609932

CALL UPDATE_LEADERS_SCORE(609933,38)

SELECT Leaders_Icon, Leaders_Score FROM CHICAGO_PUBLIC_SCHOOLS_DATA 
WHERE School_ID = 609933

CALL UPDATE_LEADERS_SCORE(609935,101)

SELECT Leaders_Icon, Leaders_Score FROM CHICAGO_PUBLIC_SCHOOLS_DATA 
WHERE School_ID = 609935